#!/usr/bin/env python3

"""
nso2elf -o sdk.nss sdk
readelf -s --wide sdk.nss | make_stub.py -o stub.S
"""

from io import StringIO
from typing import NamedTuple, TextIO

class Symbol(NamedTuple):
    name: str
    size: int
    weak: bool

def parse(text: TextIO) -> list[Symbol]:
    syms: list[Symbol] = []
    started: bool = False
    for row in text.read().splitlines():
        if not started:
            if row == "   Num:    Value          Size Type    Bind   Vis      Ndx Name":
                started = True
        else:
            entries: list[str] = row.split()
            if entries[6] == "UND" or entries[4] == "LOCAL":
                continue
            syms.append(Symbol(entries[7], int(entries[2]), entries[4] == "WEAK"))
    return syms

def create_stub_file(syms: list[Symbol]) -> str:
    out: StringIO = StringIO()
    out.write("// Autogenerated library stub - don't manually edit\n\n")
    for sym in syms:
        out.write(f"{sym.name}:\n")
        if sym.weak:
            out.write(f"    .weak {sym.name}\n")
        else:
            out.write(f"    .global {sym.name}\n")
        # out.write(f"    .size {sym.name}, {sym.size}\n")
    return out.getvalue()

if __name__ == "__main__":
    import argparse
    from pathlib import Path
    import sys

    parser: argparse.ArgumentParser = argparse.ArgumentParser("make_stub")
    parser.add_argument("--out", "-o", help="Output file path", default="lib_stub.S")
    parser.add_argument("input_file_path", nargs="?", help="Input file path", default="")

    args, _ = parser.parse_known_args()

    infile: TextIO
    if args.input_file_path:
        file: Path = Path(args.input_file_path)
        if not file.is_file():
            sys.stderr.write(f"Failed to open file {args.input_file_path}\n")
            sys.exit(1)
        infile = open(file)
    else:
        infile = sys.stdin

    syms: list[Symbol] = parse(infile)
    stub: str = create_stub_file(syms)

    outfile: Path = Path(args.out)
    outfile.parent.mkdir(parents=True, exist_ok=True)
    outfile.write_text(stub)